src/main.rs

The `jk new` command was not properly inserting new lines into the output.
The output printer when using -o with `jk new` is using the wrong log macro.

[JK-130] Fix issues with jk new command

---

.github/workflows/main.yml

This was preventing the macos runner from picking up the job.

JK-236: fix macos runner to have proper name

---

Cargo.lock
Cargo.toml
src/main.rs

The standard windows command prompt (i.e. not the new "Terminal") has known issues with color printing. This addresses the issue for Jikken.

Fix colors in windows command prompt

---

src/executor.rs
src/logger.rs
src/main.rs

Have the SimpleLogger support buffered output. When buffered output is enabled, log statements higher than INFO are buffered until a call to flush. This allows for cleaner output when executing tests. Caveats are there is now mutex locking (right now, no contention because we are single threaded) when you log above INFO level. This only happens when you run in debug or trace mode. To mitigate, I could search for/create a lock free queue implementation.

Cleaner output

---

src/executor.rs
src/main.rs

We should return a failure exit code when a test fails in order to get red vs green builds in CICD. I've retained existing printing behavior which is the cause for the (perhaps unexpected) amount of code.

Return failure exit code when a test fails

---

CHANGELOG.md
src/config.rs
src/executor.rs
src/telemetry.rs

This is not intended for use except by Jikken developers (it allows us to point our telemetry to the dev environment).

JK-365: Add dev-ingestion configuration

---

src/logger.rs

From `print!` description:
> Prints to the standard output.
> Equivalent to the [`println`] macro except that a newline is not printed at the end of the message.
> **Note that stdout is frequently line-buffered by default so it may be necessary to use `io::stdout().flush` to ensure the output is emitted immediately.**

JK-401: Add stdout flush after info logs to force print of partial line

---

example_tests/complex_checks/inline_body_schema.jkt
src/executor.rs
src/new.rs
src/test/definition.rs
src/test/file.rs
src/test/template.rs
src/test/variable.rs

- String variables shouldn't have "max" and "min'. They should have "maxLength" and "minLength" . 
- Factor out common behavior of all the specification types into `Specification` that can be leveraged by each type through composition. 
- Reimplement numeric type specifications to eliminate copied code.  
- Move off of animechan in favor of Jikken APIs
- Remove dead code from the variable module ( we should probably migrate specification-related code to that module)

JK-443 -- Better String Variables

---

example_tests/complex_checks/body_schema_variable.jkt
src/config.rs
src/new.rs
src/test.rs
src/test/file.rs
src/test/template.rs
src/test/variable.rs

- The List type can be heterogeneous
- The Object type can now not only hold DatumSchemas but serde_json::Value's as well
- All literal variables are now serde_json::Value's
- Literal variables now support strings, numbers, lists, and objects
- No longer will you specify explicit value variables in the following form due to above
`name: foo
type: String
value: hello world
`
- BodySchemas can now be specified with variables, 
- AnyOf constraint introduced which allows you to say that any of the following schema's can match vs OneOf which says that ONLY 1 may match. This really shines for lists and most users won't even need it for that, but it does offer ultimate flexibility.
- Lists can specify max and min lengths
- You can specify that a list should have any_of OR one_of OR none_of …

Jk-464 -- Improve List and Object Variables

---

example_tests/complex_checks/body_schema_variable.jkt
src/test.rs
src/test/definition.rs
src/test/file.rs
src/test/validation.rs

Support variables in body and bodyschema. Introduce a new type for variable references with special deserialization rules to make this easier. Probably the basis for variable existence validation.

JK-469 -- Support for variables in more places

---

src/new.rs
src/test/definition.rs
src/test/file.rs

We will now recognize OAS schemas, in both responses and requests, and create samples of each as part of our test template process. This allows clients to just update the generated requests and responses for the specific scenarios they wish to test.

JK-472 -- Improve OpenApi Schema Support

---

CHANGELOG.md

The actual changes are:
```
Bugfixes:
- CLI output now properly flushes prior to test completion (for long-running tests)
- Each run of a test iteration now correctly counts as a distinct test
- Test Definitions no longer include global variables in telemetry, which fixes an issue that could result in a non-steady test id
```

JK-495: added missing bugfixes from the CHANGELOG.

---

src/config.rs

Secrets are masked and sent as part of the "globals" vector. They should not also be sent as a separate structure (which is unfortunately unmasked).

JK-497: add skips to serializing secrets for config objects

---

src/main.rs
src/new.rs
src/test.rs
src/test/file.rs
src/validated.rs

To specify exact length, instead of having the same value for minLength and maxLength.

JK-498: Add length field for string and list generation/validation

---

Cargo.lock
Cargo.toml
src/test/file.rs

Changed random name to generation to randomly select from existing lists of common given and surnames.

JK-509: Update name generation and remove library

---

src/config.rs

Contains the current timestamp (`YYYY-MM-DD hh:mm:ss.sss`) in local and UTC timezones.

JK-507: Add NOW and NOW_UTC globals

---

src/test/file.rs

- Integer - between 0 and 100
- Float - between 0 and 100 with up to 3 decimal places
- String - between 5 and 20 characters
- If only min is specified, max will be greater of 20 or double the min
- If only max is specified, min will be lesser of 5 or half of max
- Email - 5-20 character random string followed by "@example.com", "@example.net", or "@example.org"
- Date/DateTime
- Default - between minimum date (1970-01-01) and now
- If only min is specified, max year is greater of current year or min year + 10

JK-513: Implement sensible defaults for randomly generated values

---

src/test/file.rs

Same behavior as generating a random integer.

JK-513: Adjust default list generation to limit integers to between 1 and 100

---

src/test.rs

Must contain at least one character, and may only contain letters, numbers, hyphens, and underscores.
Example of full message:
> Test "Generate all the things" failed validation: variable "body.invalid" name is invalid - must only contain alphanumeric characters, hyphens, and underscores.

JK-517: Add validation for variable names

---

src/new.rs
src/test/file.rs

Since we removed the `request.bodySchema` field, generating from an OpenAPI spec with request body constraints will now create an embedded variable called "body".

JK-505: Update new from OpenAPI to create variable instead of request bodySchema

---

src/executor.rs
src/telemetry.rs
src/test.rs
src/test/validation.rs

Also update test dependency graph to identify tests by index instead of id

JK-538: Make test id optional and remove auto-generation

---

Cargo.lock
Cargo.toml
src/config.rs
src/executor.rs
src/main.rs
src/telemetry.rs
src/updater.rs

We had some users request a config option to bypass cert verification.
As part of this change I upgraded to the latest hyper and associated libraries to maintain low level data processing. We will likely need to cleanup our req/resp handling soon.

JK-562: Add support for bypassing cert verification
