jikkenio/jikken

CHANGELOG.md
Cargo.lock
README.md

Updating the README documentation
Adding a CHANGELOG
Updating cargo.lock dependency versions

Update documentation for V0.1.0 Release

---

Cargo.lock
Cargo.toml
README.md

Published v0.1.0 to crates.io and updated the documentation to reflect this change.

Update README and Crates Release Documentation

---

.choco/VERIFICATION.txt
jikken.nuspec
windows_installer.nsi

This should have been done in the original PR for releasing v0.4.0
I've updated my version release runbook to not forget these steps in the future.

update windows package manager and installer versions

---

Cargo.lock
Cargo.toml
src/config.rs
src/main.rs

Add support for a home folder based configuration file.
Also refactored the code around configs to be a cleaner abstraction into a separate module.

update configuration handling, add support for user path config

---

src/errors.rs
src/executor.rs
src/main.rs
src/new.rs
src/telemetry.rs
src/updater.rs

Extracted templating to separate file.
Eliminated redundant command parsing
Removed passing CLI object through test executor.

refactored main entrypoint funtion

---

Cargo.lock
Cargo.toml
src/executor.rs

Basis for parallel tests. A follow up PR would add the scheduling and output synchronization logic.

Concurrent test basis resolved

---

src/executor.rs
src/main.rs

cargo fmt was not running on save before, so there are some formatting changes mixed in.

Better feedback when missing requires test

---

src/executor.rs

I mistakenly introduced an implicit requirement that names be unique. Only IDs must be unique. This had the noticeable effect of tests not being scheduled and a corresponding warning being issued.

Names don't have to be unique

---

src/main.rs

Support ignoring directories, files, and glob patterns

Ignore file support

---

example_tests/flaky.jkt
src/executor.rs
src/test.rs
src/test/template.rs
src/test/validation.rs
vscode_extension/syntaxes/jikken.tmLanguage.json

A case could be made for transitive disablement, but it could be considered "magic" ( also, its a bit of work )

Support for disabling tests

---

example_tests/flaky.jkt
src/executor.rs
src/main.rs
src/telemetry.rs
src/test.rs
src/test/validation.rs

When adding tests for my project, I found myself wanting the ability to list tests easily (including tag filtering).

List files

---

CHANGELOG.md
Cargo.lock
Cargo.toml
jikken.nuspec
src/new.rs
src/telemetry.rs
src/test.rs
src/test/definition.rs
src/updater.rs
windows_installer.nsi

Bump versions to 0.7.0
Update CHANGELOG
Clean-up clippy concerns
Update dependency packages

JK-353: Prep for release 0.7.0

---

README.md
src/executor.rs

JK-407 Change the displayed slash type in CLI

JK-407 Change the displayed slash type in CLI

---

src/executor.rs
src/main.rs

…t files found and fix an issue with calculating skipped files

JK-422 -- Error when iteration greater than one

---

src/executor.rs
src/new.rs
src/telemetry.rs
src/test.rs
src/test/file.rs

Also fixed most of the Clippy errors in a separate commit.

JK-441: Send skipped test telemetry data

---

example_tests/complex_checks/body_schema_variable.jkt
src/config.rs
src/new.rs
src/telemetry.rs
src/test.rs
src/test/definition.rs
src/test/file.rs
src/test/http.rs
src/test/template.rs

A continuing work in progress, but I think this is something we'll want ( in its present state ) before releasing. To protect the remaining structs will require moving away from "flatten".

JK-71 -- Better Validation of extraneous fields

---

src/test/file.rs

We lost this in the shuffle of variable stuff going on. Added this back, mostly for modifier support. I can't find a way to maintain untagged and tagged deserialization in serde, so I went with this approach/hack instead that accomplishes it.

JK-475 -- Allow data type variables to be given a value again

---

example_tests/complex_checks/inline_body_schema.jkt
src/test/file.rs

JK-477 -- Ignore support for bodySchema

JK-477 -- Strict for BodySchema, Ignore Support for BodySchema

---

example_tests/complex_checks/body_schema_variable.jkt
example_tests/complex_checks/inline_body_schema.jkt
example_tests/login.jkt
example_tests/status_v2.jkt
example_tests/value_generation/body_schema.jkt
example_tests/value_generation/body_schema_varible.jkt
example_tests/value_generation/integer_value_generation.jkt
example_tests/variables/login_using_file_body_variable.jkt
example_tests/variables/login_using_file_string_variable.jkt
example_tests/variables/login_using_string_variable.jkt

Better tags to allow example tests to be more descriptive, useful, and easily filtered.

JK-479 -- Better tags for example tests.

---

src/test.rs
src/test/file.rs
src/test/variable.rs

of variable parsing by using serde alias

JK-503 -- DateTime modifiers generation issue. Also, improve flexibility
